### PR TITLE
Fix all inputs containing non-ASCII characters got garbled

### PR DESCRIPTION
**Pull request by snakamura**
As of network-2.4.1.0, Network.URI.unEscapeString converts an input to a Unicode string assuming the input is UTF-8 encoded bytes, as well as decodes the percent-encoding. As a result, this library converts all inputs to Unicode strings, then truncates all characters in the strings to 8bits with Data.ByteString.Lazy.Char8.pack.

I copied unEscapeString from the old network library that just unescapes the percent-encoding.

### CODE REVIEW

**Comment by jgm** [comment]
It would be great to get this fixed.  An old CGI script no longer handles unicode correctly, and I don't see a way to work around it.  Nor is there an alternative cgi library to use.  This is a really bad one!

**Comment by cheecheeo** [comment]
@jgm @snakamura Is this still an issue in the `network` library? Do you still need to see these changes get merged?

**Comment by jgm** [comment]
+++ John Chee [Sep 06 14 14:54 ]:

>   [1]@jgm [2]@snakamura Is this still an issue in the network library? Do
>   you still need to see these changes get merged?

I don't know -- the cgi package was broken for long enough that
I found alternatives, so now I don't use it.

**Comment by snakamura** [comment]
Yes, I think we still need to apply this patch. I've been using cgi-3001.1.8.5 with this patch and network-2.5.0.0 and it works fine.

**Comment by cheecheeo** [comment]
@snakamura I've merged your `unescape` branch into the `next` branch of cheecheeo/haskell-cgi. Since it's a behavior modifying change it will require a major version bump.

**Comment by snakamura** [comment]
Thank you!

**Pull request closed without merging**
