### PR TITLE
Expose Network.CGI.Multipart.

### PR DESCRIPTION
**Pull request by hesselink**
I needed a multipart/mixed parser and pretty printer, and the cgi package seemed to have the best/only complete one. However, it was not exposed. This commit exposes the module.

### CODE REVIEW

**Comment by bergmark** [comment]
+1, any chance this will be merged?

**Comment by cheecheeo** [comment]
@hesselink @bergmark Would you still like to see this change merged? I've recently taken over maintainership over at https://github.com/cheecheeo/haskell-cgi and am interested in improving `cgi`.

**Comment by hesselink** [comment]
@cheecheeo We've since pulled out the multipart stuff into the [multipart package](http://hackage.haskell.org/package/multipart), since we used it in [rest](http://silkapp.github.io/rest/) which we were open sourcing. I guess it would be nice if the two remained in sync, so e.g. bugs only have to be fixed once. We could either move to use cgi once this PR is merged, or cgi could depend on multipart and remove its own (identical) multipart code. What do you think?

**Comment by bergmark** [comment]
I would prefer multipart to remain a separate package since it has much fewer dependencies. This is the only part of cgi we're using.

**Comment by cheecheeo** [comment]
I agree that it would be nice if the two remained in sync. I'm working on a branch that attempts to delete as much of `Network.CGI.Multipart` and `Network.CGI.Header` as possible but I'm running into issues because `Network.CGI` uses `showContentType` but it's not exported by `Network.Multipart.Header`, I can make more progress but what are your thoughts on exporting part of `Network.Multipart.Header`?

**Comment by bergmark** [comment]
I think the export list we chose was pretty arbitrary so feel free to export anything you need.

**Comment by hesselink** [comment]
Since the latest cgi release depends on multipart, I'll close this issue.

**Pull request closed without merging**
